apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstance
metadata:
  name: fingerprint-id
spec:
  defaultCodeRepository: 'https://github.com/redhat-na-ssa/demo-rosa-sagemaker.git'
  instanceType: ml.m5.4xlarge
  lifecycleConfigName: lifecycle-from-github
  notebookInstanceName: fingerprint-id
  roleARN: 'arn:aws:iam::000000000000:role/AmazonSageMaker-ExecutionRole'
  volumeSizeInGB: 5