apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstance
metadata:
  name: fingerprint-id
  annotations:
    recommendedInstanceType: ml.p3.8xlarge
spec:
  # NOTICE: There is no CRD for CodeRepository (manual creation) 
  defaultCodeRepository: 'https://github.com/redhat-na-ssa/demo-rosa-sagemaker.git'
  instanceType: ml.m5.4xlarge
  lifecycleConfigName: lifecycle-from-github
  notebookInstanceName: fingerprint-id
  roleARN: 'arn:aws:iam::000000000000:role/AmazonSageMaker-ExecutionRole'
  # BUG: volumeSizeInGB is a required field if you want the operator to not lose its mind
  volumeSizeInGB: 5
